name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "result=$(npm config get cache)" >> "${GITHUB_OUTPUT}"
    - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: ${{ steps.npm-cache-dir.outputs.result }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci
      shell: bash
