name: Publish Extensions
run-name: Publish Extensions (${{ github.sha }})

on:
  push:
    branches:
      - main

concurrency:
  group: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup

      # Publish
      - run: npm run publish
        env:
          RAY_TOKEN: ${{ secrets.RAYCAST_ORGANIZATION_TOKEN }}
